import { createActionGroup, emptyProps, props } from '@ngrx/store';

export const RecognitionActions = createActionGroup({
  source: 'Recognition',
  events: {
    'Connect': props<{ id: string }>(),
    'Disconnect': props<{ id: string }>(),
    'Error': props<{ error: string }>(),
    'Pause': emptyProps(),
    'Pause Success': emptyProps(),
    'Resume': emptyProps(),
    'Resume Success': emptyProps(),
    'Connect success': emptyProps(),
    'Connect failure': props<{ error: string }>(),
    'Disconnect success': emptyProps(),
    'Disconnect failure': props<{ error: string }>(),
    'Reset state': emptyProps(),
    'Init Transcript DB': props<{ userId: string }>(),
    'Init Transcript DB Success': emptyProps(),
    'DeInit Transcript DB': emptyProps(),
    'DeInit Transcript DB Success': emptyProps(),
    'Init Transcript': emptyProps(),
    'Init Transcript Success': props<{ transcriptId: number }>(),
    'Init Transcript Failure': props<{ error: string }>(),
    'Add Transcript Segment': props<{ text: string, start: Date | undefined }>(),
    'Add Transcript Segment Success': emptyProps(),
    'Add Transcript Segment Failure': props<{ error: string }>(),
    'Finalize Transcript': emptyProps(),
    'Finalize Transcript Success': emptyProps(),
    'Finalize Transcript Failure': props<{ error: string }>(),
    'Delete Transcript DB': emptyProps(),
    'Delete Transcript DB Success': emptyProps(),
    'Delete Transcript DB Error': props<{ error: string}>(),
		'Set Engine': props<{engine: 'web' | 'azure' }>(),
		'Set Engine Success': props<{engine: 'web' | 'azure' }>(),
		'Set Engine Failure': props<{error: string}>(),
		'Load Engine': emptyProps(),
    'Reset Engine': emptyProps(),
  },
});
