blank_issues_enabled: true
contact_links:
  - name: ZipCaptions Discord
    url: https://discord.gg/Swe2JeHnPc
    about: If you have questions about using ZipCaptions or need additional help, please join the Discord server.